/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ff40e90a-d0e9-45c4-a460-0b5c1ba33662",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_h1asEAvFv",
    "aws_user_pools_web_client_id": "4hcaef50vleqivro9otetfp5df",
    "oauth": {}
};


export default awsmobile;
